// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using saitynai_server.Data;

#nullable disable

namespace saitynai_server.Migrations
{
    [DbContext(typeof(TablegamesContext))]
    partial class TablegamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("saitynai_server.Entities.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<DateTime>("EditDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExchangeToGameId")
                        .HasColumnType("int");

                    b.Property<int>("FkClientId")
                        .HasColumnType("int");

                    b.Property<int>("FkGameId")
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeToGameId");

                    b.HasIndex("FkClientId");

                    b.HasIndex("FkGameId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("saitynai_server.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("FkUserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("saitynai_server.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<DateTime>("EditDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FkAdvertisementId")
                        .HasColumnType("int");

                    b.Property<int>("FkClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkAdvertisementId");

                    b.HasIndex("FkClientId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("saitynai_server.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<int?>("Difficulty")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayers")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayers")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("saitynai_server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("saitynai_server.Entities.Advertisement", b =>
                {
                    b.HasOne("saitynai_server.Entities.Game", "ExchangeToGame")
                        .WithMany()
                        .HasForeignKey("ExchangeToGameId");

                    b.HasOne("saitynai_server.Entities.Client", "FkClient")
                        .WithMany()
                        .HasForeignKey("FkClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saitynai_server.Entities.Game", "FkGame")
                        .WithMany()
                        .HasForeignKey("FkGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeToGame");

                    b.Navigation("FkClient");

                    b.Navigation("FkGame");
                });

            modelBuilder.Entity("saitynai_server.Entities.Client", b =>
                {
                    b.HasOne("saitynai_server.Entities.User", "FkUser")
                        .WithMany()
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("saitynai_server.Entities.Comment", b =>
                {
                    b.HasOne("saitynai_server.Entities.Advertisement", "FkAdvertisement")
                        .WithMany()
                        .HasForeignKey("FkAdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saitynai_server.Entities.Client", "FkClient")
                        .WithMany()
                        .HasForeignKey("FkClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkAdvertisement");

                    b.Navigation("FkClient");
                });
#pragma warning restore 612, 618
        }
    }
}
